apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  namespace: wordpress
  labels:
    app: wordpress
    env: dev
data:
  WORDPRESS_DB_HOST: "mariadb-service.mariadb.svc.cluster.local"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_DB_USER: "wordpress"
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz                ## base64 encoded value of original password - command: echo -n wordpress | base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress
spec:
  selector:
    matchLabels:
      version: v1           # Pod label to be used by Service to select the pods from this deployment
  replicas: 1                 # number of replica of the Pods
  template:
    metadata:
      labels:
        env: dev         # Pod's label
        app: wordpress
        version: v1
    spec:
      containers:
      - name: wordpress-container
        image: ramakrishna41/wordpress      # which image it will use
        ports:
        - containerPort: 80     # Port exposed by container inside the Pod
        envFrom:
          - configMapRef:
              name: wordpress-configmap
              optional: false
          - secretRef:
              name: wordpress-secret
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
  labels:
    version: v1       # label of the service
spec:
  type: ClusterIP
  ports:
  - port: 80            # the port on which the service is listening
    targetPort: 80      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    app: wordpress       # Pod label that service is using to select Pods
    version: v1
    env: dev